language: cpp

os:
  - linux
  - osx


osx_image: xcode8.3

dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev libflann-dev
      - g++-4.9

compiler:
  - clang
  - gcc

install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       :
     else
       # Linux; special handling in order to ensure that the build
       # uses a more modern GCC version.
       if [ "$CXX" = "g++" ]; then
         export CXX="g++-4.9" CC="gcc-4.9";
     fi'

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
