language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libflann-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
