language: cpp

os:
  - linux
  - osx

env:
  global:
    - MAKEFLAGS="-j 2"

osx_image: xcode8.3

dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev libflann-dev libeigen3-dev
      - libgomp1
      - g++-4.9

compiler:
  - clang
  - gcc

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" == "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
